steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/github-cloudbuild-example:${TAG_NAME}', '.']
images:
- 'gcr.io/${PROJECT_ID}/github-cloudbuild-example:${TAG_NAME}'
